# .devcontainer/docker-compose.yml
services:
  bot:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-}
      - DATABASE_URL=postgresql://postgres:password@db/bot
    volumes:
      - ..:/workspace
